import type { Metadata } from 'next';
import { Provider } from '@/components/ui/provider';
import { ReservationProvider } from '@/components/reservationProvider';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { getReservation } from '@/lib/apis';
import { Flex } from '@chakra-ui/react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('GET Reservation by uuid');
  // const reservationInfo = await getReservation();
  const reservationInfo = null;

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReservationProvider defaultInfo={reservationInfo}>
          <Provider>
            <Flex
              gap="32px"
              alignItems="center"
              justifyContent="center"
              p="8"
              h="100vh"
            >
              <Flex
                direction="column"
                alignItems="center"
                w="100%"
                maxW="600px"
                pb="6"
              >
                {children}
              </Flex>
            </Flex>
          </Provider>
        </ReservationProvider>
      </body>
    </html>
  );
}
