import fs from 'fs';

import type { Metadata } from 'next';
import { Provider } from '@/components/ui/provider';
import { ReservationProvider } from '@/components/ReservationProvider';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Flex } from '@chakra-ui/react';

async function initDB() {
  try {
    await fs.promises.readFile('./db/data.json', 'utf-8');
  } catch (e) {
    console.log(e);
    fs.mkdir('db', async (err) => {
      if (!err) {
        await fs.promises.writeFile(
          './db/data.json',
          JSON.stringify({
            reservations: [],
          }),
          'utf8'
        );
      }
    });
  }
}

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  initDB();

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReservationProvider>
          <Provider forcedTheme="light">
            <Flex
              gap="var(--layout-gap)"
              alignItems="center"
              justifyContent="center"
              p="8"
              h="100vh"
            >
              <Flex
                direction="column"
                alignItems="center"
                w="100%"
                h="100%"
                maxW="600px"
                pb="6"
              >
                {children}
              </Flex>
            </Flex>
          </Provider>
        </ReservationProvider>
      </body>
    </html>
  );
}
